version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      target: dev
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/app
      - /frontend/node_modules
      - /app/.next
    ports:
      - "3000:3000"
